### ISSUE TITLE
New release version

### ISSUE THREAD

**Issue by rschollmeyer** [spring-projects/spring-credhub#49]
So we are working with the **1.1.0.BUILD-SNAPSHOT** version at the moment and we were wondering if there will be a new **RELEASE** version soon?

**Comment by scottfrederick** [comment]
@rschollmeyer Note that I've changed the `1.1.0` version numbering to `2.0.0`. The latest snapshot builds are `2.0.0.BUILD-SNAPSHOT`, and a `2.0.0.M1` has been published. I'm getting ready to make the last set of updates for `2.0.0` and publish another milestone.

The next `2.0.0` milestone will depend on Spring Framework 5.1, Spring Security 5.1, and Spring Boot 2.1. These versions are necessary in order to get OAuth2 support for both an imperative `RestTemplate`-based interface and a reactive `WebClient`-based interface. Will these Spring dependency upgrades work for you?

**Comment by scottfrederick** [comment]
@jhiemer @Zee-Khan @seilc1 See the note above on Spring dependency versions for Spring CredHub `2.0.0` releases. Please let me know if these dependencies will cause any problems for you.
