### ISSUE TITLE
Broken links in the document

### ISSUE THREAD

**Issue by parth-pandit** [spring-projects/spring-credhub#70]
Hi There, 

I have located several broken links for CredHub references for the document of this project at [Spring CredHub](https://docs.spring.io/spring-credhub/docs/2.0.1.RELEASE/reference/html5/).

Some examples are below.

- https://credhub-api.cfapps.io/version/2.0/#get-version
- https://credhub-api.cfapps.io/version/2.0/#mutual-tls

**Comment by scottfrederick** [comment]
The docs deep-link into the [CredHub API docs](https://credhub-api.cfapps.io), using a version `2.0` that was current as of the last time the docs were updated. That version has since been removed from the CredHub API docs. 

I can update the version for future Spring CredHub docs releases, but I'm discussing with the CredHub team if there's a better way to make sure this doesn't happen again.

**Comment by scottfrederick** [comment]
Fixed for latest [snapshot release](https://docs.spring.io/spring-credhub/docs/2.0.2.BUILD-SNAPSHOT/reference/html5/) via https://github.com/spring-projects/spring-credhub/commit/6754da6a607744a7454dc4aeb9a6a45c45beb2d5
